document.write("<script>");
document.write("var coll = document.getElementsByClassName(\"collapsible\");");
document.write("var i;");
document.write("for (i = 0; i < coll.length; i++) {");
document.write("coll[i].addEventListener(\"click\", function() {");
document.write("this.classList.toggle(\"active\");");
document.write("var content = this.nextElementSibling;");
document.write("if (content.style.maxHeight){");
document.write("content.style.maxHeight = null;");
document.write("} else {");
document.write("content.style.maxHeight = content.scrollHeight + \"px\";");
document.write("}");
document.write("});");
document.write("}");

document.write("window.smoothScroll = function(target){");
document.write("var scrollContainer = target;");
document.write("do {");
document.write("scrollContainer = scrollContainer.parentNode;");
document.write("if (!scrollContainer) return;");
document.write("scrollContainer.scrollTop += 1;");
document.write("} while (scrollContainer.scrollTop == 0);");
document.write("var targetY = 0;");
document.write("do {");
document.write("if (target == scrollContainer) break;");
document.write("targetY += target.offsetTop;");
document.write("} while (target = target.offsetParent);");
document.write("scroll = function(c, a, b, i) {");
document.write("i++; if (i > 30) return;");
document.write("c.scrollTop = a + (b - a) \/ 30 * i;");
document.write("setTimeout(function(){ scroll(c, a, b, i); }, 20);");
document.write("}");
document.write("\nscroll(scrollContainer, scrollContainer.scrollTop, targetY, 0);");
document.write("}");
document.write("</script>");

document.write("<script src = \"jquery/jquery-3.5.1.min.js\"></script>");
document.write("<script>");
document.write("$(function(){");
document.write("var myRegExp = \/^.*\\#(.*)\/;");
document.write("var section = myRegExp.exec(window.location.href)[1];");
document.write("document.getElementById(section).click();");
document.write("});");
document.write("</script>");

document.write("<script>");
document.write("expandElement = function(target)");
document.write("{");
document.write("var targetElement = document.getElementById(target);");
document.write("var elementClass = targetElement.className;");
document.write("if(!elementClass.includes(\"active\"))");
document.write("{");
document.write("targetElement.click();");
document.write("}");
document.write("};");
document.write("</script>");