document.write("<img src = \"images/drawerIcon.ico\" class = \"menuToggle\" onClick = \"toggleNav()\"></img>");
document.write("<a href = \"index.html\"><img class = \"headerImg\" src = \"images/logo.png\"></img></a>");
document.write("<input id = \"searchBar\" type = \"text\" placeholder = \"Search..\" onfocus = \"this.placeholder = ''\" onblur = \"this.placeholder = 'Search..'\"></input>");
document.write("<a href = \"about.html\" class = \"headerTab\" id = \"aboutTab\">About</a>");

document.write("<script>");
document.write("function toggleNav()");
document.write("{");
document.write("var sideNav = document.getElementsByClassName(\"sidenav\").item(0);");
document.write("var main = document.getElementsByClassName(\"main\").item(0);");
document.write("if(screen.width > 481)");
document.write("{");
document.write("var sideNavWidth = \"15%\";");
document.write("var marginLeftWidth = \"25%\";");
document.write("var marginLeftWidthOff = \"10%\";");
document.write("}");
document.write("else");
document.write("{");
document.write("var sideNavWidth = \"100%\";");
document.write("var marginLeftWidth = \"0%\";");
document.write("var marginLeftWidthOff = \"0%\";");
document.write("}");
document.write("if([\"0px\", \"0%\", \"0\"].includes(getComputedStyle(sideNav).width))");
document.write("{");
document.write("sideNav.style.width = sideNavWidth;");
document.write("main.style.marginLeft = marginLeftWidth;");
document.write("document.getElementsByClassName(\"navButton\").item(0).style.marginLeft = marginLeftWidth;");
document.write("}");
document.write("else");
document.write("{");
document.write("sideNav.style.width = \"0\";");
document.write("main.style.marginLeft = marginLeftWidthOff;");
document.write("document.getElementsByClassName(\"navButton\").item(0).style.marginLeft = marginLeftWidthOff;");
document.write("}");
document.write("}");
document.write("</script>");