document.write("<div class = \"sidenav\">");
document.write("<a style=\"font-weight:bold;color:orange;\">Navigation</a>");
document.write("<HR class = \"orangeRow\">");
document.write("<a href = \"index.html\">Introduction</a>");
document.write("<a href = \"usefulOnlineResources.html\">Useful Online Resources</a>");
document.write("<a href = \"safetyNotice.html\">Safety Notice</a>");
document.write("<a href = \"whatIsASignal.html\">What is a Signal?</a>");
document.write("<a href = \"simplifyingAssumptions.html\">Simplifying Assumptions</a>");
document.write("<a href = \"componentsAndTools.html\">Components and Tools</a>");
document.write("<a href = \"importantConcepts.html\">Important Concepts</a>");
document.write("<a href = \"mxrDistortionPlus.html\">Dissecting the MXR Distortion+</a>");
document.write("</div>");