document.write("<script>");
document.write("window.smoothScroll = function(target){");
document.write("var scrollContainer = target;");
document.write("do {");
document.write("scrollContainer = scrollContainer.parentNode;");
document.write("if (!scrollContainer) return;");
document.write("scrollContainer.scrollTop += 1;");
document.write("} while (scrollContainer.scrollTop == 0);");
document.write("var targetY = 0;");
document.write("do {");
document.write("if (target == scrollContainer) break;");
document.write("targetY += target.offsetTop;");
document.write("} while (target = target.offsetParent);");
document.write("scroll = function(c, a, b, i) {");
document.write("i++; if (i > 30) return;");
document.write("c.scrollTop = a + (b - a) / 30 * i;");
document.write("setTimeout(function(){ scroll(c, a, b, i); }, 20);");
document.write("}");
document.write("scroll(scrollContainer, scrollContainer.scrollTop, targetY, 0);");
document.write("}");
document.write("</script>");